name: Give Typecoins

on:
  schedule:
    - cron: "0 16 28-31 * *"
  workflow_dispatch:

jobs:
  check-last-day:
    runs-on: ubuntu-latest
    outputs:
      lastday: ${{ steps.lastday.outputs.lastday }}
    steps:
      - name: Check last day of month
        id: lastday
        run: echo "::set-output name=lastday::$(($(date -d +1day +%d) == 1))"
  give-typecoins:
    needs: check-last-day
    if: needs.check-last-day.outputs.lastday == 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
      - name: Run Script
        env:
          BONUSLY_API_TOKEN: ${{ secrets.BONUSLY_API_TOKEN }}
          OPEN_AI_API_TOKEN: ${{ secrets.OPEN_AI_API_TOKEN }}
          TENOR_API_TOKEN: ${{ secrets.TENOR_API_TOKEN }}
        run: PYTHONPATH=. python typecoin/main.py
