name: Give Typecoins

on:
  schedule:
    - cron: "0 16 28-31 * *"
  workflow_dispatch:

jobs:
  check-last-day:
    runs-on: ubuntu-latest
    outputs:
      lastday: ${{ steps.lastday.outputs.lastday }}
    steps:
      - name: Check last day of month
        id: lastday
        run: echo "::set-output name=lastday::$(($(date -d +1day +%d) == 1))"
  give-typecoins:
    needs: check-last-day
    if: needs.check-last-day.outputs.lastday == 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup Python
        uses: actions/setup-python@v2.3.2
        with:
          python-version: "3.8"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --no-dev --no-root
      - name: Run Script
        env:
          BONUSLY_API_TOKEN: ${{ secrets.BONUSLY_API_TOKEN }}
        run: poetry run python main.py
